---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
spec:
  replicas: 2
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: deployment
      version: v01
  template:
    metadata:
      labels:
        app: deployment
        version: v01
    spec:
      containers:
      - name: deployment
        image: apurvbidkar/kubernetes_project
        ports:
        - containerPort: 80
