kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: Devops
   template:
     metadata:
       name: testpod1
       labels:
         name: Devops
     spec:
      containers:
        - name: nginx
          image: apurvbidkar/kubernetes_project
          imagePullPolicy: Never
          ports:
          - containerPort: 80
