kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod
       labels:
         name: deployment
     spec:
      containers:
        - name: mycontainer
          image: apurvbidkar/kubernetes_project
          imagePullPolicy: Always
          ports:
          - conatainerPort: 80

