kind: Service                             
apiVersion: v1
metadata:
  name: serviceipdemo
spec:
  ports:
    - port: 80                             
      targetPort: 80              
  selector:
    name: Devops                 
  type: NodePort
