kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: deployment
spec:
  ports:
    - port: 8080                             # Containers port exposed
      targetPort: 80
      nodePort: 31200      # Pods port
  selector:
    name: deployment                    # Apply this service to any pods which has the specific label
  type: LoadBalancer                   # Specifies the service type i.e ClusterIP or NodePort

