kind: Service                             
apiVersion: v1
metadata:
  name: serviceipdemo
spec:
  ports:
    - port: 80                             
      targetPort: 80 
      nodePort: 31200      
  selector:
    name: Devops                 
  type: LoadBalancer
